### PR TITLE
Upgrade to Play 2.6 RC1

### PR DESCRIPTION
**Pull request by mkurz**
https://groups.google.com/d/topic/play-framework/div4xgSVsjo/discussion

### CODE REVIEW

**Comment by schaloner** [comment]
Wow, Travis CI is really struggling with the new version of Play https://travis-ci.org/schaloner/deadbolt-2-java/builds/235131453

**Comment by mkurz** [comment]
The bintray repo it the problem. Takes ages and ends in "Service error" messages when trying to open dependency urls in the browser.
Probably we have to wait until they fixed their service.

**Comment by mkurz** [comment]
bintray_error

**Comment by schaloner** [comment]
http://status.bintray.com/

All Systems Operational Refreshed less than 1 minute ago
Website Operational
REST API Operational
Downloads Operational
Past Incidents
May 23, 2017
No incidents reported today.
May 22, 2017
No incidents reported.

I'll let them know they have an issue

**Comment by mkurz** [comment]
I sent them an email as well already.

**Pull request merged**
