### PR TITLE
Always check all constraints

### PR DESCRIPTION
**Pull request by mkurz**
**Following situation:**
We have two roles. Therefore our users belong to either role1 (BACKOFFICE) or role2 (SALES) - but that two roles share (better: can have) the same permissions. Because of that we don't use the deadbolt role-based-permissions feature - since an admin user is able to assign each permission to each user separately (doesn't matter which role a user belongs to), so a (set of) permission(s) is **not** bound to a specific role.
Like this:

| (user)    | (role)     | write_post | send_newsletter | add_new_user |
|-----------|------------|------------|-----------------|--------------|
| mkurz     | BACKOFFICE |            | [x]             | [x]          |
| schaloner | SALES      | [x]        | [x]             |              |
| ltorvalds | BACKOFFICE |            |                 | [x]          |
| swozniak | SALES |  [x]            |                 | [x]          |

As you can see the permissions are assigned randomly to the users (and therefore to the roles).

We now have two controllers:
```java
@Restrict(@Group("BACKOFFICE"))
public class Controller1 extends Controller {

	@Pattern("send_newsletter")
	public CompletionStage<Result> someAction() {
		// ...
	}
}
```
```java
@Restrict(@Group("SALES"))
public class Controller2 extends Controller {

	@Pattern("send_newsletter")
	public CompletionStage<Result> someOtherAction() {
		// ...
	}
}
```
**What is the problem we are facing?**

If `mkurz` - a `BACKOFFICE` user - accesses `Controller2.someOtherAction` he is allowed to do so. WAT? I thought only `SALES` people are allowed to access `Controller2`? Why? I can tell you why: Because as soon as deadbolt encounters a succesfull constraint check (in this case `@Pattern("send_newsletter")` on `someOtherAction` - `mkurz` does have this permission) it marks the action method "authorised". Which means any constraint checks that come later (in our case - because by default action method annotations are executed before controller annotations -   `@Restrict(@Group("SALES"))` on the `Controller2` class itself) don't even bother checking their constraints but just continue execution the action composition chain (by checking `isActionAuthorised` [here](https://github.com/schaloner/deadbolt-2-java/blob/v2.6.3/code/app/be/objectify/deadbolt/java/actions/AbstractRestrictiveAction.java#L50), [here](https://github.com/schaloner/deadbolt-2-java/blob/v2.6.3/code/app/be/objectify/deadbolt/java/actions/BeforeAccessAction.java#L50) and [here](https://github.com/schaloner/deadbolt-2-java/blob/v2.6.3/code/app/be/objectify/deadbolt/java/actions/AbstractSubjectAction.java#L59)).

So I am asking myself: **Is this a feature or a bug?**

Because we do **not** want that an action gets executed as soon as **only one** constraint passes its check - we want that **every** restriction and pattern (and other constraints) *which are in the current action composition chain* pass before an action is allowed to be executed.

Steve, do you get my thoughts?

So what this pull request does it introduces a `deadbolt.java.always-check-all-constraints` boolean setting (which is `false` by default to keep backward compatibility), which - when enabled - just ensures that an action never gets marked as "authorised" meaning that every subsequent constraint in the action composition chain has to really do it's check. (If you come up with a better name for the config flag tell me).

If you ask me I find the current behaviour a bit unsafe... I definitely would expect that all restrict, pattern, etc, of an action AND its controller (and superclass controller) pass before executing the action method....

This behaviour even results in weirdness like this:
```java
	@Restrict(@Group("SALES"))
	@Pattern("send_newsletter")
	public CompletionStage<Result> someSuperMegaSafeAction() {
		// ...
	}
```
So in this example we would now only check if a user has the `SALES` group (because that one comes first) but wouldn't care about the `send_newsletter` permission because the action would be "authorised" by the first check already. So even `swozniak` - which is defined as a sales guy but doesn't have the `send_newsletter` permission would nevertheless get access to this `someSuperMegaSafeAction` (to maybe send out some sneaky newsletters he isn't supposed to do?).

We could go even further and change the [Play default behaviour](https://github.com/playframework/playframework/blob/2.6.6/framework/src/play/src/main/resources/reference.conf#L114-L115) so controller annotations come before action methods annotations. For our `Controller1` and `Controller2` above that of course would result into that we would just care about the role on the controller-level but not about the permission on the action-method-level.

If you ask me again I would say just completely remove [markActionAsAuthorised](https://github.com/schaloner/deadbolt-2-java/blob/v2.6.3/code/app/be/objectify/deadbolt/java/actions/AbstractDeadboltAction.java#L176) and [isActionAuthorised](https://github.com/schaloner/deadbolt-2-java/blob/v2.6.3/code/app/be/objectify/deadbolt/java/actions/AbstractDeadboltAction.java#L199) and never ever mark an action "authorised".
Or maybe I just don't get that there is a deeper sense behind this methods...

### CODE REVIEW

**Comment by schaloner** [comment]
This is a designed feature, allowing the developer to define general controller-level restrictions but being able to specialize on specific methods.  I think if we change this behavior, it could cause some very obscure issues for existing code-bases.

One idea that could combine these two differing approaches could be to add an extra parameter to each constraint, allowing for the method-level restriction to be AND'd (or OR'd, or whatever, if we use an enum instead of a boolean) with the controller-level restriction.  To maintain backwards compatibility, the default behavior  would be to only use the method-level  constraint if present and otherwise fall back to the controller-level constraint.

**Comment by mkurz** [comment]
> This is a designed feature, allowing the developer to define general controller-level restrictions but being able to specialize on specific methods.

This works as long as I dont set `play.http.actionComposition.controllerAnnotationsFirst = true`, then it will change the other way round (which is ok if you want to use it that way). I think the whole problem is the behaviour is not documented anywhere that's why I expected something else (at least I couldn't find it quickly).

> I think if we change this behavior, it could cause some very obscure issues for existing code-bases.

Sure, that's why my pr is backward compatible :smile: 

> One idea that could combine these two differing approaches could be to add an extra parameter to each constraint, allowing for the method-level restriction to be AND'd (or OR'd, or whatever, if we use an enum instead of a boolean) with the controller-level restriction. To maintain backwards compatibility, the default behavior would be to only use the method-level constraint if present and otherwise fall back to the controller-level constraint.

My thoughts:
How do we even know if the current executed annotation action was defined on controller level or on method level? In the moment we are in a Play (annotations) actions `call` method we only get a `Http.Context ctx` passed. I don't really know how do get this information out without hacking Play to provide us that information ([this](https://github.com/playframework/playframework/blob/2.6.6/framework/src/play/src/main/scala/play/core/j/JavaAction.scala#L40-L44) is where to start :smile: As you can see it ends up in a list of `allDeclaredAnnotations` which then will be called one after each other - which, as you know, is called "action composition". However Play will [not pass the information](https://github.com/playframework/playframework/blob/2.6.6/framework/src/play/src/main/scala/play/core/j/JavaAction.scala#L92-L98) of *where* the annotation of such an action was defined originally).
**So we can't distinguish between controller-level and method-level constraints right now because of that limitation of the framework.**

However, lets assume for a moment we *could* distinguish between controller-level and method-level constraints. What about this now:
```java
	@Restrict(@Group("SALES"))
	@Pattern("send_newsletter")
	public CompletionStage<Result> someSuperMegaSafeAction() {
		// ...
	}
```
We have two constraints on method level. What should we do here? Right now the behaviour is to skip the second one in case the first one already marks the action as "authorised" (which I find very weird and actually think thats a bug because this has nothing to do with controller-level vs method-level constraint as both are on method-level. The second constraint will **never** be checked because if the first fails the game is over and if succeeds the next one wont even be checked anymore because of the "authorised" marking thing. I am not sure if that was by design...)
Applying your idea if we now have an AND or OR parameter on the first constraint should we now AND also with the second constraint? Or again ignore the second constraint and just use that AND for the controller-level constraint - if we define one. And what about if the second constraint would define the opposite parameter of the first one (AND vs OR). What to do now (if it even will be called)?
However that are just theoretical problems we can't solve right now anyway because we can't distinguish controller level vs method level constraints....

**The key point** (for me at least):
We for example always want to `AND` **all** constraints that apply to an action - no matter where that constraints are defined along the way (you could say "all the constraints on an action's action composition chain have to pass" before allowing the action to execute).
Applying your idea (and having solved the problems above) would (at least) mean we always would have to set the `AND` parameter on each constraint. So if just one dev just one time forgets to add such an `AND` parameter, well then we are pretty much fucked.
**That's why I - *even if we would implement your idea* - still would like to be able to set the default of all constraints to `AND` - and that is what my pull request is doing.** We could rename the config to something different like `constraints-default-mode = AND` or something (instead of `always-check-all-constraints` in this pr). Right now the mode is probably best described as something like `constraints-default-mode = SKIP_ON_FIRST_SUCCESS`. That's how we can make sure globally a dev is not fucking something up by *forgetting* to set a parameter.
That approach would allow us to add different default modes in future. Also we could add the parameter you mentioned any time later (because I am not willing to work on this right now because of other priorities).
**So that `constraints-default-mode` would just be the default mode for constraints that do not define that parameter.**

What do you think?
If OK I can change this pull request to use `constraints-default-mode = AND` (and keep it `SKIP_ON_FIRST_SUCCESS` by default to stay backward compatible - or however you want to name it). We can add modes and parameters later.

I really would like to get a solution in with the next minor release (by end of this week?)

Thanks!

**Comment by mkurz** [comment]
Maybe the current mode is better descriped as `PROCESS_FIRST_CONSTRAINT_ONLY` because a second constraint will never be processed...

**Comment by mkurz** [comment]
Steve, I hacked Play to provide us more information about the origin and the precursor of an action inside the action composition chain:
https://github.com/playframework/playframework/pull/7964
https://github.com/playframework/playframework/pull/7965
We could use this stuff for deadbolt 2.7.

I will update this pull request today or the coming ones. I was pondering a while and I think it's a good approach to add something like `constraints-default-mode` which can be set to `AND` and `OR` (besides the default). I will implement at least the `AND` mode (which is basically this pr) and if I find time the `OR` part (I already know what needs to be done).

**Comment by schaloner** [comment]
I'll review all these at the weekend.  Thanks for the PRs!

**Comment by mkurz** [comment]
I am working on this right now.

**Comment by mkurz** [comment]
I am not completely finished yet with this pull request, I will update tomorrow.

**Comment by mkurz** [comment]
Still not finished...

**Pull request merged**
