### PR TITLE
supor play 2.4

### PR DESCRIPTION
**Pull request by vmouta**
- remove unused SimpleResult imports
- use injections
- use play version 2.4.0-M3

### CODE REVIEW

**Comment by mkurz** [comment]
@schaloner Play 2.4.0 RC2 is out. Any chance we see deadbolt support for play 2.4 soon? Thanks!

**Comment by schaloner** [comment]
Working on it, it's a question of time at the moment. Pull requests are welcome!

**Comment by mkurz** [comment]
Play 2.4 has been released: https://groups.google.com/forum/?fromgroups=#!topic/play-framework-dev/De4-4sp2fL0 :smile:

**Comment by schaloner** [comment]
`"be.objectify" %% "deadbolt-java" % "2.4.0-SNAPSHOT"` should give what you you're looking for.  Documentation coming later today, but the release notes on https://github.com/schaloner/deadbolt-2-java should be enough to get you started.

**Comment by schaloner** [comment]
https://github.com/schaloner/deadbolt-2-java-examples has been updated for 2.4

**Pull request closed without merging**
