### PR TITLE
Fix travis (use 2.6 Final)

### PR DESCRIPTION
**Pull request by mkurz**

### CODE REVIEW

**Comment by mkurz** [comment]
https://github.com/playframework/playframework/pull/7445 made in Play 2.6 Final but wasn't in RC-2 yet that's why we need to override `public List<EssentialFilter> getFilters()` now.

**Comment by mkurz** [comment]
green

**Comment by mkurz** [comment]
The VersionEye check doesn't really work...

**Comment by schaloner** [comment]
I think we can remove VersionEye.  I'll get this merged and released some time today.  Thanks for the good work!

**Comment by mkurz** [comment]
Great, thank you!

**Comment by mkurz** [comment]
Just FYI - Play 2.6.1 was released

**Comment by schaloner** [comment]
This has been released as 2.6.1

**Comment by mkurz** [comment]
Thank you!

**Pull request merged**
