### PR TITLE
[2.7] Remove unnecessary ExecutionContextProvider

### PR DESCRIPTION
**Pull request by mkurz**
### Do NOT merge yet, this has to wait for the 2.7 release because it breaks backward compatibility.
Hi Steve,

I saw you released `2.6.3` and with it removed all those `xxxAsync(...)` calls to which we passed an execution context explicitly.
If you ask me I think we can just remove the whole `ExecutionContextProvider` because there is no need for it anymore now.

The only places left where we used an execution context are `AbstractDeadboltHandler.java` to render Play's default `unauthorized` page (which definitly doesn't need to happen async) and in `DefaultSubjectCache.java` to put the subject into the `context.args` - if caching applies (I also don't see why this `put` operation should happen async).

What do you think?

I may open one or two more pull requests with other enhancements soon.

### CODE REVIEW

**Comment by schaloner** [comment]
I'm happy to do this in 2.7, but I'm reluctant to remove it in a patch release when people might be using it.  I'll move this to future enhancements unless there's a compelling argument otherwise?

**Comment by mkurz** [comment]
Another pr is coming later this evening or tomorrow. Off for some :beers:

**Comment by mkurz** [comment]
Alright I split the parts which remove the last two `*Async()` calls out to #52. That one should be fine to merge now without breaking anything. I will afterwards rebase this pull request here so it stays open so you can merge it for 2.7 later (which then just removes the unused ´ExecutionContextProvider`.
OK for you?

**Comment by mkurz** [comment]
I rebased this pull request - feel free to merge it as soon as you are working on deabolt 2.7. (Ping me in case there are merge conflicts later on so I can quickly rebase again)

**Comment by schaloner** [comment]
Thanks.  I'll keep this open for now - no idea whenPlay 2.7 is coming out.

**Comment by mkurz** [comment]
After this got merged we also have to update the docs.

**Pull request merged**
