### PR TITLE
Allow to make code blocking

### PR DESCRIPTION
**Pull request by mkurz**
Proposal of a fix for #7
(This is WIP)

### CODE REVIEW

**Comment by mkurz** [comment]
TODO:
 - [ ] Not sure about `JavaAnalyzer.java`
 - [ ] Time out setting

**Comment by schaloner** [comment]
I'll go over this tonight, but first impressions are it's a [million to one shot](http://www.goodreads.com/quotes/229767-million-to-one-chances-crop-up-nine-times-out-of-ten)...that might just work.

**Comment by schaloner** [comment]
One comment - the blocking timeout should be configurable from application.conf.

**Comment by mkurz** [comment]
I know I will add this later.

**Comment by mkurz** [comment]
Done - the blocking timeout is now configurable.
Also I removed the `TODO` from `JavaAnalyzer` and left it untouched - it only gets called from `ViewSupport.viewPattern` which resolved the future already.

**Comment by mkurz** [comment]
@schaloner I did **lots of** load testing with our apps yesterday *the whole day*. I am sure now this PR here fixed the JPA issue reliably. We are going in production with this and I feel comfortable with it :smile: 

For the record:
I can confirm there are very very likely deadlocks when `@Transactional` uses `withTransactionAsync` (no matter if you set `deadbolt.java.blocking` to `true` or `false`), so it was a good choice in Play 2.4 to move to `withTransaction`.
When using `withTransaction` in the annotation (as I said the default in Play 2.4 now) *and* setting `deadbolt.java.blocking` to `true` I never ever ran into a deadlock again, no matter how high the load was. The only important thing is that in case you offload some work like this
```java
Akka.system().scheduler().scheduleOnce(Duration.create(1L, TimeUnit.SECONDS), () -> {
	play.db.jpa.JPA.withTransaction(() -> {
		// something
	});
}, Akka.system().dispatchers().lookup("my-context"));
```
is that you do **NOT** use the play default thread pool `Akka.system().dispatcher()` but instead any custom thread pool (in the example above `my-context`. Otherwise you might still run into deadlocks on high load.
That's the only thing someone has to be aware and take care of.

For me the JPA issue is resolved and imho #7 can be closed.
Thanks for merging!

**Comment by johdah** [comment]
@mkurz Nice, I will test it when I get JPA to work. :wink:

**Comment by schaloner** [comment]
@mkurz Excellent news, thanks for your work!

**Comment by schaloner** [comment]
@mkurz if you're convinced by this, I'll release it as 2.4.1 this evening.

**Comment by mkurz** [comment]
@schaloner Back from vacation. Did you release 2.4.1? It's not available via maven...

**Comment by schaloner** [comment]
Not yet - I wanted your confirmation first.

**Comment by mkurz** [comment]
For me its fine - go ahead!

**Comment by johdah** [comment]
It has worked good for me as well!

**Comment by johdah** [comment]
Released yet?

**Comment by schaloner** [comment]
Happening today - just got back from vacation.

**Comment by schaloner** [comment]
Released as `"be.objectify" %% "deadbolt-java" % "2.4.1"`

**Comment by mkurz** [comment]
@schaloner thanks a lot!

**Pull request merged**
